# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
version: '3'
services:
  redis-srv:
    image: redis
    ports:
      - '6379:6379'
